---
- hosts: web_Servers
  become: true
  tasks:

  - name: Install Web Server
    tags: apache,apach2,webserver
    apt:
      name:
        - apache2
      state: latest

  - name: Copy Default html file for site
    tags: html,apache2,apache
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: File_Servers
  become: true
  tasks:

  - name: Install Unzip
    tags: zip,unzip
    apt: 
      name: unzip

  - name: Install Terraform
    unarchive:
        src: https://releases.hashicorp.com/terraform/1.9.4/terraform_1.9.4_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes # we are just telling linux that you dont have to look for the src because its link
        mode: 0755
        owner: root
        group: root