---
- hosts: all
  become: true
  pre_tasks:

  - name: Update Repository
    tags: Always
    apt:
      update_cache: yes

- hosts: web_Servers
  become: true
  tasks:

  - name: Download Web Servers (Nginx and Apache)
    tags: nginx,apache,apache2,debian
    apt:
      name:
        - apache2
        - nginx

- hosts: db_Servers
  become: true
  tasks:

  - name: Download SQLmap
    tags: mysql,sql
    apt:
      name: git
      state: latest

- hosts: File_Servers
  become: true
  tasks:

  - name: Install Samba
    tags: samba
    package:
        name:
          - samba
        state: latest
